### ISSUE TITLE
Inner div not filling outer div in card.

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/Interactives#1]
CSS problems... killing me.

**Comment by pgonzbecer** [comment]
... Try making the card have "display: table;" and the front and back as "display: table-cell;". Not sure if that will do the trick but I am unable to access a computer as of right now. It did the trick for the docking thing in OpenGraph

**Comment by johnRedden** [comment]
Does not appear to work...  I am pretty sure it is doable.

**Comment by pgonzbecer** [comment]
Look at the opengraph js and try and immitate what I did to get the heights accordingly, its alittle weird to do it but it works

**Comment by pgonzbecer** [comment]
*html, and it is called the collapser, collapse container, and collapse content.

**Comment by johnRedden** [comment]
I gave up and did it programmatically... I had the width from the slider
anyway.  The card flipper put a magical spell on that flipping element?
The inner padding was an issue too.
