### ISSUE TITLE
Displaying Text : Venn Diagram

### ISSUE THREAD

**Issue by pgonzbecer** [johnRedden/Interactives#2]
There's got to be a better way to display the text on the venn diagram, and for it to display text when they intersect

**Comment by johnRedden** [comment]
I was thinking of bootstrap tooltip or popovers... http://getbootstrap.com/javascript/#popovers-examples

**Comment by pgonzbecer** [comment]
New Issue! I didn't want to make a new one because it is basically the same thing, whenever you try and display the tooltip for the first circle, it makes the second circle disappear for some reason

**Comment by johnRedden** [comment]
instead of calling pep on an entire class... maybe should be individual
objects??:

$(".vennCircle").pep

(http://pep.briangonzalez.org/)

**Comment by johnRedden** [comment]
Ok, no that does not work.

**Comment by pgonzbecer** [comment]
Haha ok. I was going to say, it takes out the generality of the diagram, only one per page basically

**Comment by johnRedden** [comment]
maybe if they  both have different parents?  Or we abandon PEP for
something else?

**Comment by pgonzbecer** [comment]
hmm, tricky, but crazy enough to work

**Comment by johnRedden** [comment]
Even still... the tooltip is "blinky" ... will have to solve that problem
as well.  Maybe, we try another dragging solution?

**Comment by johnRedden** [comment]
Looks like we use this to do it manually:  https://github.com/jquery/PEP

http://jquery.github.io/PEP/tracker/

**Comment by pgonzbecer** [comment]
Or we can keep the regular pep and just use the jquery-ui's tooltip. the one we are currently using does not have it but it is definately there.
http://api.jqueryui.com/tooltip/

I tried using this link instead for the script:
http://code.jquery.com/ui/1.11.4/jquery-ui.js
and it works fine, just some css work need to be done.

There is a conflict with bootstrap, but that seems to be fixable:
http://stackoverflow.com/questions/23428285/bootstrap-and-jqueryui-conflict
http://getbootstrap.com/javascript/#js-noconflict

Good?

**Comment by johnRedden** [comment]
I think learning regular pep is worthwhile...  wait, which pep are you
talking about?

https://github.com/jquery/PEP

https://github.com/briangonzalez/jquery.pep.js/

The jquery ui that we have has draggable in it... which is not good for
touch anyway.  I am ok with jquery tooltip.  You solve... I am a bit under
the weather with a headache.

I do think we need to figure out the touch events to work (pointer events)
for all devices.  This will extend to everything else we do.  J

**Comment by pgonzbecer** [comment]
Alright, then we will stick with the https://github.com/jquery/PEP pep. Don't worry about it, I feel really close to finishing this thing anywho, plus theres the GDG and SURGE today, so just rest I suppose.

**Comment by johnRedden** [comment]
Good choice I think!  No big deadline on this though.

Yeah, I am going to nap it up till GDG.  Thanks.

**Comment by pgonzbecer** [comment]
Long time coming, but for got the tooltip out the way, it should be mobile friendly too
